g = traversal().withRemote('conf/remote-graph.properties')
v1 = g.addV('v').property('name', 'marko').property('age', 29).next()
v2 = g.addV('v').property('name', 'vadas').property('age', 27).next()
v3 = g.addV('v').property('name', 'lop').property('lang', 'java').next()
v4 = g.addV('v').property('name', 'josh').property('age', 32).next()
v5 = g.addV('v').property('name', 'ripple').property('lang', 'java').next()
g.V(v1).addE('e').to(v2).property('weight', new Float(0.1)).next()
g.V(v1).addE('e').to(v2).property('weight', new Float(0.2)).next()
g.V(v1).addE('e').to(v2).property('weight', new Float(0.3)).next()
g.V(v1).addE('e').to(v2).property('weight', new Float(0.4)).next()
g.V(v1).addE('e').to(v2).property('weight', new Float(0.5)).next()
g.V(v1).addE('e').to(v3).property('weight', new Float(0.6)).next()
g.V(v1).addE('e').to(v5).property('weight', new Float(0.6)).next()
g.V(v3).addE('e').to(v4).property('weight', new Float(0.7)).next()
g.V(v3).addE('e').to(v4).property('weight', new Float(0.8)).next()
g.V(v3).addE('e').to(v4).property('weight', new Float(0.9)).next()
g.V(v3).addE('e').to(v4).property('weight', new Float(1.0)).next()
g.V(v5).addE('e').to(v5).property('weight', new Float(2.0)).next()
g.V(v5).addE('e').to(v5).property('weight', new Float(3.0)).next()
g.V(v5).addE('e').to(v5).property('weight', new Float(4.0)).next()
