version: "3"

services:
  puppygraph-query:
    image: puppygraph/puppygraph-query:latest
    container_name: puppygraph-query
    environment:
      - PUPPYGRAPH_USERNAME=puppygraph
      - PUPPYGRAPH_PASSWORD=puppygraph123
      - PORT=8081
      - GREMLINSERVER_HOST=janusgraph:8182
    networks:
      janusgraph_net:
    ports:
      - "8081:8081"
  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph
    networks:
      janusgraph_net:
    ports:
      - "8182:8182"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
networks:
  janusgraph_net:
    name: puppy-janusgraph
